// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajSivLPSEyA3aicjrEqcMM
// Component: mdoUGzJrsxpyi
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: G_Ak2YrPD5H3-/component
import Button from "../../Button"; // plasmic-import: xIlhGXFJi7gxml/component
import CopyrightSocialLanguage from "../../CopyrightSocialLanguage"; // plasmic-import: wtR1cNL3-xgah/component
import { useScreenVariants as useScreenVariantsjf6FV4VwSlEHz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Jf6fV4vwSlEHz/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: ajSivLPSEyA3aicjrEqcMM/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: mdoUGzJrsxpyi/css
import EmailIcon from "./icons/PlasmicIcon__Email"; // plasmic-import: YNPQWSZis2grCm/icon
import DeliveryIcon from "./icons/PlasmicIcon__Delivery"; // plasmic-import: jqsdHKqHx71qw6/icon
import EnterIcon from "./icons/PlasmicIcon__Enter"; // plasmic-import: bX6Fmep2HbrJ5u/icon
import QuestionIcon from "./icons/PlasmicIcon__Question"; // plasmic-import: J-dULpUoY0aNd8/icon

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjf6FV4VwSlEHz()
  });

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__jwXc)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__cpdkQ)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___7UiY6
            )}
          >
            {"Subscribe"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uzSfi
            )}
          >
            {
              "Sign up for exclusive offers, original stories, activism, events and more."
            }
          </div>

          <TextInput
            data-plasmic-name={"textInput"}
            data-plasmic-override={overrides.textInput}
            className={classNames("__wab_instance", sty.textInput)}
            placeholder={"Email address..."}
            showStartIcon={true}
            startIcon={
              <EmailIcon
                className={classNames(projectcss.all, sty.svg___8W8M0)}
                role={"img"}
              />
            }
          />

          <Button
            className={classNames("__wab_instance", sty.button__nRhFf)}
            colors={"black"}
          >
            {"Sign me up"}
          </Button>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__l9Via)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__pXlMl
            )}
          >
            {"Help"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__nGpiW)}
          >
            <Button
              showStartIcon={true}
              startIcon={
                <DeliveryIcon
                  className={classNames(projectcss.all, sty.svg__heDGu)}
                  role={"img"}
                />
              }
            >
              {"Order status"}
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__dG4Mi)}
              showStartIcon={true}
              startIcon={
                <EnterIcon
                  className={classNames(projectcss.all, sty.svg__x83Q)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__soCUp
                )}
              >
                {"Returns and exchanges"}
              </div>
            </Button>

            <Button
              className={classNames("__wab_instance", sty.button__i391F)}
              showStartIcon={true}
              startIcon={
                <QuestionIcon
                  className={classNames(projectcss.all, sty.svg__qbTSq)}
                  role={"img"}
                />
              }
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__c0EcA
                )}
              >
                {"Help center"}
              </div>
            </Button>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__bWuBn)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zxQpO
            )}
          >
            {"More info"}
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__b8ZQo)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__uMhb)}
            >
              <Button>{"Gift cards"}</Button>

              <Button
                className={classNames("__wab_instance", sty.button__hjugQ)}
              >
                {"Find a store"}
              </Button>

              <Button
                className={classNames("__wab_instance", sty.button__l1Ca6)}
              >
                {"Careers"}
              </Button>

              <Button
                className={classNames("__wab_instance", sty.button__mvYlD)}
              >
                {"Sitemap"}
              </Button>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__poYXm)}
            >
              <Button
                className={classNames("__wab_instance", sty.button__cw8Uj)}
              >
                {"Group sales"}
              </Button>

              <Button
                className={classNames("__wab_instance", sty.button__atHnr)}
              >
                {"Privacy policy"}
              </Button>

              <Button
                className={classNames("__wab_instance", sty.button__wwB5Z)}
              >
                {"Contact us"}
              </Button>
            </p.Stack>
          </div>
        </p.Stack>
      </p.Stack>

      <CopyrightSocialLanguage
        data-plasmic-name={"copyrightSocialLanguage"}
        data-plasmic-override={overrides.copyrightSocialLanguage}
        className={classNames("__wab_instance", sty.copyrightSocialLanguage)}
      />
    </section>
  );
}

const PlasmicDescendants = {
  root: ["root", "textInput", "textbox", "copyrightSocialLanguage"],
  textInput: ["textInput", "textbox"],
  copyrightSocialLanguage: ["copyrightSocialLanguage"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    copyrightSocialLanguage: makeNodeComponent("copyrightSocialLanguage"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
