// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajSivLPSEyA3aicjrEqcMM
// Component: Ib5gwGrUlENTj
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: ajSivLPSEyA3aicjrEqcMM/projectcss
import sty from "./PlasmicRating.module.css"; // plasmic-import: Ib5gwGrUlENTj/css
import EmptyStarIcon from "./icons/PlasmicIcon__EmptyStar"; // plasmic-import: IZMmcWZmYA0Z9U/icon
import FullStarIcon from "./icons/PlasmicIcon__FullStar"; // plasmic-import: WtjvY5cWB9pa8U/icon
import HalfStarIcon from "./icons/PlasmicIcon__HalfStar"; // plasmic-import: JLJMdOm-5xE7vu/icon

export const PlasmicRating__VariantProps = new Array("rating");

export const PlasmicRating__ArgProps = new Array();

function PlasmicRating__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "half")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "one")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__iOc1W, {
          [sty.svgrating_five__iOc1Wpoe7S]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__iOc1WZl9Lk]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__iOc1WUYdv3]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_half__iOc1W4KQyz]: hasVariant(
            variants,
            "rating",
            "half"
          ),

          [sty.svgrating_oneHalf__iOc1War6NK]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_one__iOc1WdkBf7]: hasVariant(
            variants,
            "rating",
            "one"
          ),

          [sty.svgrating_threeHalf__iOc1WDX6O]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__iOc1WG0TEw]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__iOc1WDijRo]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__iOc1WACv8X]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "oneHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "two")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__pV5Ve, {
          [sty.svgrating_five__pV5VEpoe7S]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__pV5VeZl9Lk]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__pV5VeuYdv3]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_oneHalf__pV5VEar6NK]: hasVariant(
            variants,
            "rating",
            "oneHalf"
          ),

          [sty.svgrating_threeHalf__pV5VeDX6O]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__pV5Veg0TEw]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__pV5VeDijRo]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          ),

          [sty.svgrating_two__pV5VeaCv8X]: hasVariant(variants, "rating", "two")
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? FullStarIcon
            : hasVariant(variants, "rating", "twoHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "three")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__p5GIg, {
          [sty.svgrating_five__p5GIgpoe7S]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__p5GIgZl9Lk]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__p5GIgUYdv3]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__p5GIgDX6O]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          ),

          [sty.svgrating_three__p5GIgG0TEw]: hasVariant(
            variants,
            "rating",
            "three"
          ),

          [sty.svgrating_twoHalf__p5GIgDijRo]: hasVariant(
            variants,
            "rating",
            "twoHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "threeHalf")
            ? HalfStarIcon
            : hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "four")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? FullStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__i2P9U, {
          [sty.svgrating_five__i2P9Upoe7S]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__i2P9UZl9Lk]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          ),

          [sty.svgrating_four__i2P9UuYdv3]: hasVariant(
            variants,
            "rating",
            "four"
          ),

          [sty.svgrating_threeHalf__i2P9UDX6O]: hasVariant(
            variants,
            "rating",
            "threeHalf"
          )
        })}
        role={"img"}
      />

      <p.PlasmicIcon
        PlasmicIconType={
          hasVariant(variants, "rating", "five")
            ? FullStarIcon
            : hasVariant(variants, "rating", "fourHalf")
            ? HalfStarIcon
            : EmptyStarIcon
        }
        className={classNames(projectcss.all, sty.svg__uiKjq, {
          [sty.svgrating_five__uiKjqpoe7S]: hasVariant(
            variants,
            "rating",
            "five"
          ),

          [sty.svgrating_fourHalf__uiKjqZl9Lk]: hasVariant(
            variants,
            "rating",
            "fourHalf"
          )
        })}
        role={"img"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRating__ArgProps,
      internalVariantPropNames: PlasmicRating__VariantProps
    });

    return PlasmicRating__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRating";
  } else {
    func.displayName = `PlasmicRating.${nodeName}`;
  }
  return func;
}

export const PlasmicRating = Object.assign(
  // Top-level PlasmicRating renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRating
    internalVariantProps: PlasmicRating__VariantProps,
    internalArgProps: PlasmicRating__ArgProps
  }
);

export default PlasmicRating;
/* prettier-ignore-end */
