// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ajSivLPSEyA3aicjrEqcMM
// Component: jv2mPivqYl
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_commerce_landing_page.module.css"; // plasmic-import: ajSivLPSEyA3aicjrEqcMM/projectcss
import sty from "./PlasmicShopify.module.css"; // plasmic-import: jv2mPivqYl/css

export const PlasmicShopify__VariantProps = new Array();

export const PlasmicShopify__ArgProps = new Array();

function PlasmicShopify__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShopify__ArgProps,
      internalVariantPropNames: PlasmicShopify__VariantProps
    });

    return PlasmicShopify__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShopify";
  } else {
    func.displayName = `PlasmicShopify.${nodeName}`;
  }
  return func;
}

export const PlasmicShopify = Object.assign(
  // Top-level PlasmicShopify renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicShopify
    internalVariantProps: PlasmicShopify__VariantProps,
    internalArgProps: PlasmicShopify__ArgProps
  }
);

export default PlasmicShopify;
/* prettier-ignore-end */
